# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
  release:

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      hash: ${{ github.sha }}
      tag: ${{ github.event.release.tag_name }}
      branch: ${{ github.ref_name }}
      trigger: ${{ github.event_name }}

    steps:      
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
          
      - name: Write Env
        run: deno run -A deploy/writeEnv.ts

      - name: Build
        run: bash deploy/build.sh

      - name: Test Request
        run: deno test -A mod.test.ts
      
      - name: Deploy Prod
        if: ${{ env.branch == 'main' && env.trigger == 'release' }}
        uses: denoland/deployctl@v1
        with:
          project: enz
          entrypoint: mod.ts

      - name: Deploy Preview
        if: ${{ env.branch != 'main' }}
        uses: denoland/deployctl@v1
        with:
          project: enz
          entrypoint: mod.ts
