# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      hash: ${{ github.sha }}
      tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
      branch: ${{ github.ref_type == 'branch' && (github.head_ref || github.ref_name) || '' }}

      token: ${{ secrets.DENO_DEPLOY_TOKEN }}
      project: ${{ secrets.DENO_DEPLOY_PROJECT }}

    steps:      
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build
        run: bash deploy/build.sh

      - name: Test Request
        run: deno test -A mod.test.ts
      
      - name: Deploy Prod
        if: ${{ env.tag }}
        run: deno run -A jsr:@deno/deployctl@1.13.1 deploy --token=$token --project=$project --entrypoint=mod.ts --env=hash=${{ env.hash }} --env=tag=${{ env.tag }} --prod

      - name: Deploy Preview
        if: ${{ env.branch }}
        run: deno run -A jsr:@deno/deployctl@1.13.1 deploy --token=$token --project=$project --entrypoint=mod.ts --env=hash=${{ env.hash }} --env=branch=${{ env.branch }}
